import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <div className="nav_links">
            <Image
              alt="Illustrated logo"
              src="/nav_logo.svg"
              height={50}
              width={50}
            />
            <Link href="/">Home</Link>
            <Link href="#works">Work</Link>
            <Link href="/about">About</Link>
            <Link href="#">Email</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
